tinyMCE.addI18n('fi.advanced_dlg',{
about_title:"Tietoja TinyMCE:st\u00E4",
about_general:"Tietoja",
about_help:"Ohje",
about_license:"Lisenssi",
about_plugins:"Lis\u00E4osat",
about_plugin:"Lis\u00E4osa",
about_author:"Kirjoittaja",
about_version:"Versio",
about_loaded:"Ladatut lis\u00E4osat",
anchor_title:"Liit\u00E4/muokkaa ankkuria",
anchor_name:"Ankkurin nimi",
code_title:"HTML-koodin muokkaus",
code_wordwrap:"Automaattinen rivinvaihto",
colorpicker_title:"Valitse v\u00E4ri",
colorpicker_picker_tab:"Valitsin",
colorpicker_picker_title:"V\u00E4rin valitsin",
colorpicker_palette_tab:"Paletti",
colorpicker_palette_title:"V\u00E4ripalette",
colorpicker_named_tab:"Nimetty",
colorpicker_named_title:"Nimetyt v\u00E4rit",
colorpicker_color:"V\u00E4ri:",
colorpicker_name:"Nimi:",
charmap_title:"Valitse erikoismerkki",
image_title:"Lis\u00E4\u00E4/muokkaa kuvaa",
image_src:"Kuvan osoite",
image_alt:"Kuvan kuvaus",
image_list:"Kuvalista",
image_border:"Reunus",
image_dimensions:"Mitat",
image_vspace:"Pystysuuntainen tila",
image_hspace:"Vaakasuuntainen tila",
image_align:"Tasaus",
image_align_baseline:"Tekstin tasossa",
image_align_top:"Yl\u00F6s",
image_align_middle:"Keskelle",
image_align_bottom:"Alas",
image_align_texttop:"Tekstin yl\u00E4osaan",
image_align_textbottom:"Tekstin alaosaan",
image_align_left:"Vasemmalle",
image_align_right:"Oikealle",
link_title:"Lis\u00E4\u00E4/muuta linkki",
link_url:"Linkin osoite",
link_target:"Kohde",
link_target_same:"Avaa linkki samassa ikkunassa",
link_target_blank:"Avaa linkki uuteen ikkunaan",
link_titlefield:"Otsikko",
link_is_email:"Antamasi osoite n\u00E4ytt\u00E4\u00E4 olevan s\u00E4\u00E4hk\u00F6postiosoite. Haluatko lis\u00E4t\u00E4 siihen mailto:-etuliitteen?",
link_is_external:"Antamasi osoite n\u00E4ytt\u00E4\u00E4 johtavan ulkopuoliselle sivustolle. Haluatko lis\u00E4t\u00E4 linkin eteen http://-etuliitteen? (suositus)",
link_list:"Linkkilista"
});