tinyMCE.addI18n('gl.advanced',{
style_select:"Estilos",
font_size:"Tama\u00F1o",
fontdefault:"Fonte",
block:"Formato",
paragraph:"P\u00E1rrafo",
div:"Div",
address:"Enderezo",
pre:"Pre-formateado",
h1:"Encabezamento 1",
h2:"Encabezamento 2",
h3:"Encabezamento 3",
h4:"Encabezamento 4",
h5:"Encabezamento 5",
h6:"Encabezamento 6",
blockquote:"Bloque de cita",
code:"C\u00F3digo",
samp:"Mostra de c\u00F3digo",
dt:"Termo de definici\u00F3n",
dd:"Descripci\u00F3n de definici\u00F3n",
bold_desc:"Negrita (Ctrl+B)",
italic_desc:"Cursiva (Ctrl+I)",
underline_desc:"Subli\u00F1ado (Ctrl+U)",
striketrough_desc:"Tachado",
justifyleft_desc:"Ali\u00F1ar \u00E1 esquerda",
justifycenter_desc:"Ali\u00F1ar \u00F3 centro",
justifyright_desc:"Ali\u00F1ar \u00E1 dereita",
justifyfull_desc:"Xustificar",
bullist_desc:"Lista desordenada",
numlist_desc:"Lista ordenada",
outdent_desc:"Reducir sangr\u00EDa",
indent_desc:"Aumentar sangr\u00EDa",
undo_desc:"Desfacer (Ctrl+Z)",
redo_desc:"Re-facer (Ctrl+Y)",
link_desc:"Insertar/editar hiperv\u00EDnculo",
unlink_desc:"Quitar hiperv\u00EDnculo",
image_desc:"Insertar/editar imaxe",
cleanup_desc:"Limpiar lixo no c\u00F3digo",
code_desc:"Editar c\u00F3digo HTML",
sub_desc:"Sub\u00EDndice",
sup_desc:"Super\u00EDndice",
hr_desc:"Insertar regra horizontal",
removeformat_desc:"quitar formato",
custom1_desc:"A s\u00FAa descripci\u00F3n persoal aqu\u00ED",
forecolor_desc:"Seleccionar cor do texto",
backcolor_desc:"Seleccionar cor do fondo",
charmap_desc:"Insertar caracteres persoalizados",
visualaid_desc:"Mostrar/ocultar li\u00F1a de gu\u00EDa/elementos invisibres",
anchor_desc:"Insertar/editar \u00E1ncora",
cut_desc:"Cortar",
copy_desc:"Copiar",
paste_desc:"Pegar",
image_props_desc:"Propiedades de imaxe",
newdocument_desc:"Novo documento",
help_desc:"Axuda",
blockquote_desc:"Cita",
clipboard_msg:"Copiar/Cortar/Pegar non est\u00E1 disponible en Mozilla e Firefox.\r\n\u00BFDesexa obter mais informaci\u00F3n sobre de este asunto?",
path:"Ruta",
newdocument:"\u00BFSeguro que desexa limpar todo o contido?",
toolbar_focus:"Ir \u00F3s bot\u00F3ns de ferramentas - Alt+Q, Ir \u00F3 editor - Alt-Z, Ir \u00E1 ruta do elemento - Alt-X",
more_colors:"M\u00E1is cores"
});