tinyMCE.addI18n('gl.advanced_dlg',{
about_title:"Sobre TinyMCE",
about_general:"Sobre",
about_help:"Axuda",
about_license:"Licencia",
about_plugins:"Comprementos",
about_plugin:"Compremento",
about_author:"Autor",
about_version:"Versi\u00F3n",
about_loaded:"Comprementos cargados",
anchor_title:"Insertar/editar \u00E1ncora",
anchor_name:"Nome da \u00E1ncora",
code_title:"Editor HTML",
code_wordwrap:"Cortar li\u00F1as autom\u00E1ticamente",
colorpicker_title:"Seleccionar cor",
colorpicker_picker_tab:"Selector",
colorpicker_picker_title:"Selector de cores",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta de cores",
colorpicker_named_tab:"Nomeados",
colorpicker_named_title:"Cores nomeados",
colorpicker_color:"Cor:",
colorpicker_name:"Nome:",
charmap_title:"Seleccionar caracter personalizado",
image_title:"Insertar/editar imaxe",
image_src:"URL da imaxe",
image_alt:"Descripci\u00F3n da imaxe",
image_list:"Lista de Imaxes",
image_border:"Borde",
image_dimensions:"Dimensi\u00F3n",
image_vspace:"Espacio vertical",
image_hspace:"Espacio horizontal",
image_align:"Ali\u00F1aci\u00F3n",
image_align_baseline:"Li\u00F1a base",
image_align_top:"Arriba",
image_align_middle:"Medio",
image_align_bottom:"Abaixo",
image_align_texttop:"Texto arriba",
image_align_textbottom:"Texto abaixo",
image_align_left:"Esquerda",
image_align_right:"Dereita",
link_title:"Insertar/editar enlace",
link_url:"URL do enlace",
link_target:"Obxetivo",
link_target_same:"Abrir v\u00EDnculo na mesma vent\u00E1",
link_target_blank:"Abrir v\u00EDnculo nunha vent\u00E1 nova",
link_titlefield:"T\u00EDtulo",
link_is_email:"A URL introducida semella ser un enderezo de e-mail, \u00BFDesexa engadi-lo prefixo necesario mailto:?",
link_is_external:"A URL introducida semella ser un v\u00EDnculo externo, \u00BFDesexa engadi-lo prefixo necesario http://?",
link_list:"Lista de hiperv\u00EDnculos"
});