tinyMCE.addI18n('ms.advanced',{
style_select:"Gaya",
font_size:"Saiz Huruf",
fontdefault:"Jenis Huruf",
block:"Format",
paragraph:"Perenggan",
div:"Div",
address:"Alamat",
pre:"Telah diformatkan",
h1:"Tajuk 1",
h2:"Tajuk 2",
h3:"Tajuk 3",
h4:"Tajuk 4",
h5:"Tajuk 5",
h6:"Tajuk 6",
blockquote:"Petikan blok",
code:"Kod",
samp:"Contoh kod",
dt:"Maksud terma",
dd:"Maksud huraian",
bold_desc:"Tebal (Ctrl+B)",
italic_desc:"Condong (Ctrl+I)",
underline_desc:"Garis bawah (Ctrl+U)",
striketrough_desc:"Garis tengah",
justifyleft_desc:"Selari kekiri",
justifycenter_desc:"Selari ketengah",
justifyright_desc:"Selari kekanan",
justifyfull_desc:"Selari penuh",
bullist_desc:"Senarai tidak tertib",
numlist_desc:"Senarai tertib",
outdent_desc:"Lekuk kebelakang",
indent_desc:"Lekuk kedepan",
undo_desc:"Undur (Ctrl+Z)",
redo_desc:"Maju (Ctrl+Y)",
link_desc:"Sisip/sunting pautan",
unlink_desc:"Tiada pautan",
image_desc:"Sisip/sunting imej",
cleanup_desc:"Bersihkan kod",
code_desc:"Sunting kod HTML",
sub_desc:"Subskrip",
sup_desc:"Superskrip",
hr_desc:"Sisip pembaris mengufuk",
removeformat_desc:"Alih format",
custom1_desc:"Huraian anda di sini",
forecolor_desc:"Pilih warna teks",
backcolor_desc:"Pilih warna latar belakang",
charmap_desc:"Sisip aksara",
visualaid_desc:"Alih garis panduan/unsur tak nampak",
anchor_desc:"Sisip/sunting anchor",
cut_desc:"Potong",
copy_desc:"Salin",
paste_desc:"Tempel",
image_props_desc:"Alatan imej",
newdocument_desc:"Dokumen baru",
help_desc:"Bantuan",
blockquote_desc:"Petikan blok",
clipboard_msg:"Salin/Potong/Tempel tidak disokong dalam Mozilla dan Firefox.\r\nAdakah anda mahu informasi lanjut tentang isu ini?",
path:"Laluan",
newdocument:"Hapus semua kandungan?",
toolbar_focus:"Lompat ke butang alatan - Alt+Q, Lompat ke editor - Alt-Z, Lompat ke unsur laluan - Alt-X",
more_colors:"Warna lain"
});