tinyMCE.addI18n('nn.advanced',{
style_select:"Stilar",
font_size:"Skriftstorleik",
fontdefault:"Skriftfamilie",
block:"Format",
paragraph:"Avsnitt",
div:"Div",
address:"Adresse",
pre:"Pre-formatert",
h1:"Overskrift 1",
h2:"Overskrift 2",
h3:"Overskrift 3",
h4:"Overskrift 4",
h5:"Overskrift 5",
h6:"Overskrift 6",
blockquote:"Innrykk",
code:"Kode",
samp:"Kodeeksempel",
dt:"Definisjonsuttrykk",
dd:"Definisjonsbeskrivelse",
bold_desc:"Feit",
italic_desc:"Kursiv",
underline_desc:"Understreking",
striketrough_desc:"Gjennomstreking",
justifyleft_desc:"Venstrejustert",
justifycenter_desc:"Midtstilt",
justifyright_desc:"H\u00F8grejustert",
justifyfull_desc:"Blokkjustert",
bullist_desc:"Punktliste",
numlist_desc:"Nummerliste",
outdent_desc:"Reduser innrykk",
indent_desc:"Auk innrykk",
undo_desc:"Angre",
redo_desc:"Gjer om",
link_desc:"Set inn / endre lenkje",
unlink_desc:"Fjern lenkje",
image_desc:"Set inn / endre bilete",
cleanup_desc:"Rens grisete kode",
code_desc:"Redigere HTML-koden",
sub_desc:"Senka skrift",
sup_desc:"Heva skrift",
hr_desc:"Set inn horisontal linje",
removeformat_desc:"Fjern formatering",
custom1_desc:"Din spesialfunksjondefinisjon her",
forecolor_desc:"Vel skriftfarge",
backcolor_desc:"Vel bakgrunnsfarge",
charmap_desc:"Set inn spesialteikn",
visualaid_desc:"Sl\u00E5 av/p\u00E5 usynlige element",
anchor_desc:"Set inn / endre anker",
cut_desc:"Klipp ut",
copy_desc:"Kopier",
paste_desc:"Lim inn",
image_props_desc:"Eigenskaper for bilete",
newdocument_desc:"Nytt dokument",
help_desc:"Hjelp",
blockquote_desc:"Innrykk",
clipboard_msg:"Klipp ut / Kopier /Lim inn fungerer ikkje i Mozilla og Firefox. \r\n  Vil du vite meir om dette?",
path:"Sti",
newdocument:"Er du sikker p\u00E5 at du vil slette alt innhald?",
toolbar_focus:"Skift til verktyknappar - Alt+Q, Skift til editor - Alt-Z, Skift til elementsti - Alt-",
more_colors:"Fleire fargar"
});