tinyMCE.addI18n('ro.advanced_dlg',{
about_title:"Despre TinyMCE",
about_general:"Despre",
about_help:"Ajutor",
about_license:"Licen\u0163\u0103",
about_plugins:"Module",
about_plugin:"Modul",
about_author:"Autor",
about_version:"Versiune",
about_loaded:"Module \u00EEnc\u0103rcate",
anchor_title:"Inserare/editare ancor\u0103",
anchor_name:"Nume ancor\u0103",
code_title:"Editor surs\u0103 HTML",
code_wordwrap:"Word wrap",
colorpicker_title:"Alege\u0163i o culoare",
colorpicker_picker_tab:"Picker",
colorpicker_picker_title:"Color picker",
colorpicker_palette_tab:"Palet\u0103",
colorpicker_palette_title:"Palet\u0103 de culori",
colorpicker_named_tab:"Named",
colorpicker_named_title:"Culori denumite",
colorpicker_color:"Culoare:",
colorpicker_name:"Nume:",
charmap_title:"Alege\u0163i un caracter special",
image_title:"Insereaz\u0103/editeaz\u0103 imagine",
image_src:"URL imagine",
image_alt:"Descriere imagine",
image_list:"List\u0103 de imagini",
image_border:"Bordur\u0103",
image_dimensions:"Dimensiuni",
image_vspace:"Spa\u0163iu vertical",
image_hspace:"Spa\u0163iu orizontal",
image_align:"Aliniere",
image_align_baseline:"Baseline",
image_align_top:"Sus",
image_align_middle:"La mijloc",
image_align_bottom:"Jos",
image_align_texttop:"Textul sus",
image_align_textbottom:"Textul la mijloc",
image_align_left:"St\u00E2nga",
image_align_right:"Dreapta",
link_title:"Insereaz\u0103/editeaz\u0103 link",
link_url:"URL link",
link_target:"\u0162int\u0103",
link_target_same:"Deschide link \u00EEn aceea\u015Fi fereastr\u0103",
link_target_blank:"Deschide link \u00EEn fereastr\u0103 nou\u0103",
link_titlefield:"Titlu",
link_is_email:"URL-ul pe care l-a\u0163i introdus pare a fi o adres\u0103 de email, dori\u0163i s\u0103 adaug \u015Fi prefixul mailto: necesar?",
link_is_external:"URL-ul pe care l-a\u0163i introdus pare a fi un link extern, dori\u0163i s\u0103 adaug \u015Fi prefixul http:// necesar?",
link_list:"Lista de linkuri"
});