tinyMCE.addI18n('bs.advanced_dlg',{
about_title:"TinyMCE",
about_general:"O programu",
about_help:"Pomo\u0107",
about_license:"Licenca",
about_plugins:"Dodaci",
about_plugin:"Dodatak",
about_author:"Autor",
about_version:"Verzija",
about_loaded:"Postoje\u0107i dodaci",
anchor_title:"Umetni/uredi sidro",
anchor_name:"Ime sidra",
code_title:"HTML ure\u0111iva\u010D",
code_wordwrap:"Omatanje teksta",
colorpicker_title:"Izbor boje",
colorpicker_picker_tab:"Odabir",
colorpicker_picker_title:"Odabir boje",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta boja",
colorpicker_named_tab:"Imenovano",
colorpicker_named_title:"Imenovane boje",
colorpicker_color:"Boja:",
colorpicker_name:"Naziv:",
charmap_title:"Odaberite znak",
image_title:"Umetni/uredi sliku",
image_src:"URL slike",
image_alt:"Opis slike",
image_list:"Lista slika",
image_border:"Obrub",
image_dimensions:"Dimenzije",
image_vspace:"Okomiti razmak",
image_hspace:"Vodoravni razmak",
image_align:"Poravnavanje",
image_align_baseline:"Osnovna linija",
image_align_top:"Vrh",
image_align_middle:"Sredina",
image_align_bottom:"Dno",
image_align_texttop:"Vrh teksta",
image_align_textbottom:"Dno teksta",
image_align_left:"Lijevo",
image_align_right:"Desno",
link_title:"Umetni/uredi poveznicu",
link_url:"URL poveznice",
link_target:"Meta",
link_target_same:"Otvori poveznicu u istom prozoru",
link_target_blank:"Otvori poveznicu u novom prozoru",
link_titlefield:"Naslov",
link_is_email:"URL koji ste unijeli izgleda kao e-mail adresa, \u017Eelite li dodati potrebni mailto: prefiks?",
link_is_external:"URL koji ste unijeli izgleda kao vanjska poveznica, \u017Eelite li dodati potrebni http:// prefiks?",
link_list:"Lista poveznica"
});