tinyMCE.addI18n('da.advanced_dlg',{
about_title:"Om TinyMCE",
about_general:"Om",
about_help:"Hj\u00E6lp",
about_license:"Licens",
about_plugins:"Udvidelser",
about_plugin:"Udvidelse",
about_author:"Forfatter",
about_version:"Version",
about_loaded:"Indl\u00E6ste udvidelser",
anchor_title:"Inds\u00E6t/rediger anker",
anchor_name:"Navn p\u00E5 anker",
code_title:"HTML kildekode redigering",
code_wordwrap:"Tekstombrydning",
colorpicker_title:"V\u00E6lg en farve",
colorpicker_picker_tab:"V\u00E6lger",
colorpicker_picker_title:"Farve v\u00E6lger",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Palette farver",
colorpicker_named_tab:"Navngivet",
colorpicker_named_title:"Navngivet farve",
colorpicker_color:"Farve:",
colorpicker_name:"Navn:",
charmap_title:"V\u00E6lg specialtegn",
image_title:"Inds\u00E6t/rediger billede",
image_src:"Billede URL",
image_alt:"Billedebeskrivelse",
image_list:"Liste over billeder",
image_border:"Kant",
image_dimensions:"Dimensioner",
image_vspace:"Vertikal afstand",
image_hspace:"Horisontal afstand",
image_align:"Justering",
image_align_baseline:"Grundlinie",
image_align_top:"Toppen",
image_align_middle:"Centreret",
image_align_bottom:"Bunden",
image_align_texttop:"Tekst toppen",
image_align_textbottom:"Tekst bunden",
image_align_left:"Venstre",
image_align_right:"H\u00F8jre",
link_title:"Inds\u00E6t/rediger link",
link_url:"Link URL",
link_target:"Target",
link_target_same:"\u00C5ben link i samme vindue",
link_target_blank:"\u00C5ben link i nyt vindue",
link_titlefield:"Titel",
link_is_email:"Den URL der er indtastet ser ud til at v\u00E6re en emailadresse. Vil du have tilf\u00F8jet det p\u00E5kr\u00E6vede mailto: foran?",
link_is_external:"Den URL der er indtastet ser ud til at v\u00E6re et eksternt link. Vil du have tilf\u00F8jet det p\u00E5kr\u00E6vede http:// foran?",
link_list:"Liste over links"
});