tinyMCE.addI18n('et.advanced_dlg',{
about_title:"About TinyMCE",
about_general:"About",
about_help:"Help",
about_license:"License",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Author",
about_version:"Version",
about_loaded:"Loaded plugins",
anchor_title:"Sisesta/redigeeri ankur",
anchor_name:"Ankru nimi",
code_title:"HTML Source Editor",
code_wordwrap:"Word wrap",
colorpicker_title:"Vali v\u00E4rv",
colorpicker_picker_tab:"Korjaja",
colorpicker_picker_title:"V\u00E4rvi korjaja",
colorpicker_palette_tab:"Palett",
colorpicker_palette_title:"Palett v\u00E4rvid",
colorpicker_named_tab:"Nimetatud",
colorpicker_named_title:"Nimetatud v\u00E4rvid",
colorpicker_color:"V\u00E4rv:",
colorpicker_name:"Nimi:",
charmap_title:"Vali kohandatud t\u00E4hem\u00E4rk",
image_title:"Sisestal/redigeeri pilt",
image_src:"Pildi URL",
image_alt:"Pildi kirjeldus",
image_list:"Pildi loend",
image_border:"Raam",
image_dimensions:"Dimensioonid",
image_vspace:"Vertikaalne vahe",
image_hspace:"Horisontaalne vahe",
image_align:"Reastus",
image_align_baseline:"Kirjajoondus",
image_align_top:"\u00DClemine",
image_align_middle:"Keskmine",
image_align_bottom:"Alumine",
image_align_texttop:"Teksti tipp",
image_align_textbottom:"Teksti p\u00F5hi",
image_align_left:"Vasak",
image_align_right:"Parem",
link_title:"Sisesta/redigeeri link",
link_url:"Link URL",
link_target:"Sihtala",
link_target_same:"Ava link samas aknas",
link_target_blank:"Ava link uues aknas",
link_titlefield:"Tiitel",
link_is_email:"URL, mille te sisestasite, tundub olevat emaili aadress, kas soovite, et lisataks mailto: eesliite?",
link_is_external:"URL, mille sisestasite, tundub olevat v\u00E4line link, kas soovite, et lisataks http:// eesliite?",
link_list:"Lingi loetelu"
});