tinyMCE.addI18n('fi.advanced',{
style_select:"Tyylit",
font_size:"Fonttikoko",
fontdefault:"Fontti",
block:"Muotoilu",
paragraph:"Kappale",
div:"Div",
address:"Osoite",
pre:"Esimuotoiltu (pre)",
h1:"Otsikko 1",
h2:"Otsikko 2",
h3:"Otsikko 3",
h4:"Otsikko 4",
h5:"Otsikko 5",
h6:"Otsikko 6",
blockquote:"Pitk\u00E4 lainaus",
code:"Koodi",
samp:"Koodi esimerkki",
dt:"M\u00E4\u00E4rittelyn ehto ",
dd:"M\u00E4\u00E4rittelyn kuvaus",
bold_desc:"Lihavoitu (Ctrl+B)",
italic_desc:"Kursivoitu (Ctrl+I)",
underline_desc:"Alleviivattu (Ctrl+U)",
striketrough_desc:"Yliviivattu",
justifyleft_desc:"Tasaus vasemmalle",
justifycenter_desc:"Keskitetty",
justifyright_desc:"Tasaus oikealle",
justifyfull_desc:"Tasattu",
bullist_desc:"J\u00E4rjest\u00E4m\u00E4t\u00F6n lista",
numlist_desc:"J\u00E4rjestetty lista",
outdent_desc:"V\u00E4henn\u00E4 sisennyst\u00E4",
indent_desc:"Sisenn\u00E4",
undo_desc:"Peru (Ctrl+Z)",
redo_desc:"Tee uudelleen (Ctrl+Y)",
link_desc:"Lis\u00E4\u00E4/muuta linkki",
unlink_desc:"Poista linkki",
image_desc:"Lis\u00E4\u00E4/muuta kuva",
cleanup_desc:"Siisti sekainen koodi",
code_desc:"Editoi HTML-koodia",
sub_desc:"Alaindeksi",
sup_desc:"Yl\u00E4indeksi",
hr_desc:"Lis\u00E4\u00E4 vaakasuora viivain",
removeformat_desc:"Poista muotoilu",
custom1_desc:"Oma kuvauksesi t\u00E4h\u00E4n",
forecolor_desc:"Valitse tekstin v\u00E4ri",
backcolor_desc:"Valitse taustan v\u00E4ri",
charmap_desc:"Lis\u00E4\u00E4 erikoismerkki",
visualaid_desc:"Suuntaviivat/N\u00E4kym\u00E4tt\u00F6m\u00E4t elementit",
anchor_desc:"Lis\u00E4\u00E4/Muokkaa ankkuri",
cut_desc:"Leikkaa",
copy_desc:"Kopioi",
paste_desc:"Liit\u00E4",
image_props_desc:"Kuvan ominaisuudet",
newdocument_desc:"Uusi tiedosto",
help_desc:"Ohje",
blockquote_desc:"Pitk\u00E4 lainaus",
clipboard_msg:"Kopioi/Leikkaa/Liit\u00E4 -painikkeet eiv\u00E4t toimi Mozilla ja Firefox-selaimilla. Voit kuitenkin k\u00E4ytt\u00E4\u00E4 n\u00E4pp\u00E4inyhdistelmi\u00E4 kopioimiseen (ctrl+c), leikkaamiseen (ctrl+x) ja liitt\u00E4miseen (ctrl+v).\r\nHalutatko lis\u00E4\u00E4 tietoa?",
path:"Polku",
newdocument:"Haluatko varmasti tyhjent\u00E4\u00E4 kaiken sis\u00E4ll\u00F6n?",
toolbar_focus:"Siirry ty\u00F6kaluihin - Alt+Q, Siirry tekstieditoriin - Alt-Z, Siirry elementin polkuun - Alt-X",
more_colors:"Enemm\u00E4n v\u00E4rej\u00E4"
});