tinyMCE.addI18n('is.advanced',{
style_select:"St\u00EDlsni\u00F0",
font_size:"Leturst\u00E6r\u00F0",
fontdefault:"Leturger\u00F0",
block:"Format",
paragraph:"M\u00E1lsgrein",
div:"Div",
address:"Heimilisfang",
pre:"Forsni\u00F0i\u00F0",
h1:"Fyrirs\u00F6gn 1",
h2:"Fyrirs\u00F6gn 2",
h3:"Fyrirs\u00F6gn 3",
h4:"Fyrirs\u00F6gn 4",
h5:"Fyrirs\u00F6gn 5",
h6:"Fyrirs\u00F6gn 6",
blockquote:"Blockquote",
code:"K\u00F3\u00F0i",
samp:"K\u00F3\u00F0ad\u00E6mi",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"Feitletra (Ctrl+B)",
italic_desc:"Sk\u00E1letra (Ctrl+I)",
underline_desc:"Undirstrika (Ctrl+U)",
striketrough_desc:"Yfirstrika",
justifyleft_desc:"Vinstrijafna",
justifycenter_desc:"Mi\u00F0jujafna",
justifyright_desc:"H\u00E6grijafna",
justifyfull_desc:"Jafna",
bullist_desc:"B\u00F3lulisti",
numlist_desc:"N\u00FAmera\u00F0ur listi",
outdent_desc:"Draga \u00FAt",
indent_desc:"Draga inn",
undo_desc:"Taka til baka (Ctrl+Z)",
redo_desc:"Endurtaka (Ctrl+Y)",
link_desc:"Setja inn/breyta hlekk",
unlink_desc:"Afhlekkja",
image_desc:"Setja inn/breyta mynd",
cleanup_desc:"Hreinsa sk\u00EDtugan k\u00F3\u00F0a",
code_desc:"Breyta HTML k\u00F3\u00F0a",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Setja inn l\u00E1r\u00E9tta l\u00EDnu",
removeformat_desc:"Hreinsa sni\u00F0",
custom1_desc:"L\u00FDsingin \u00FE\u00EDn h\u00E9r",
forecolor_desc:"Veldu lit texta",
backcolor_desc:"Veldu bakgrunnslit",
charmap_desc:"Setja inn t\u00E1kn",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Setja inn/breyta akkeri",
cut_desc:"Klippa",
copy_desc:"Afrita",
paste_desc:"L\u00EDma",
image_props_desc:"Stillingar myndar",
newdocument_desc:"N\u00FDtt skjal",
help_desc:"Hj\u00E1lp",
blockquote_desc:"Blockquote",
clipboard_msg:"Afrita/Klippa/L\u00EDma er ekki a\u00F0gengilegt \u00ED Mozilla og Firefox eins og er.\nViltu f\u00E1 n\u00E1nari uppl\u00FDsingar?",
path:"Sl\u00F3\u00F0",
newdocument:"Ertu viss um a\u00F0 \u00FE\u00FA viljir hreinsa allt?",
toolbar_focus:"Hoppa \u00ED t\u00F3lastiku - Alt+Q, Hoppa \u00ED ritil - Alt-Z, Hoppa \u00ED sl\u00F3\u00F0 - Alt-X",
more_colors:"Fleiri litir"
});