tinyMCE.addI18n('is.advanced_dlg',{
about_title:"Um TinyMCE",
about_general:"Um",
about_help:"Hj\u00E1lp",
about_license:"Leyfi",
about_plugins:"Vi\u00F0b\u00E6tur",
about_plugin:"Vi\u00F0b\u00E6tur",
about_author:"H\u00F6fundur",
about_version:"\u00DAtg\u00E1fa",
about_loaded:"Vi\u00F0b\u00E6tur \u00ED notkun",
anchor_title:"Setja inn/breyta akkeri",
anchor_name:"Nafn akkeris",
code_title:"HTML k\u00F3\u00F0a ritill",
code_wordwrap:"Word wrap",
colorpicker_title:"Veldu lit",
colorpicker_picker_tab:"Veljari",
colorpicker_picker_title:"Litaveljari",
colorpicker_palette_tab:"Litaspjald",
colorpicker_palette_title:"Litir litaspjalds",
colorpicker_named_tab:"Nefndir",
colorpicker_named_title:"Nefndir litir",
colorpicker_color:"Litur:",
colorpicker_name:"Nafn:",
charmap_title:"Veldu t\u00E1kn",
image_title:"Setja inn/breyta mynd",
image_src:"Sl\u00F3\u00F0 myndar",
image_alt:"L\u00FDsing myndar",
image_list:"Myndalisti",
image_border:"Rammi",
image_dimensions:"St\u00E6r\u00F0ir",
image_vspace:"L\u00F3\u00F0r\u00E9tt loftun",
image_hspace:"L\u00E1r\u00E9tt loftun",
image_align:"J\u00F6fnun",
image_align_baseline:"Baseline",
image_align_top:"Toppur",
image_align_middle:"Mi\u00F0ja",
image_align_bottom:"Botn",
image_align_texttop:"Toppur texta",
image_align_textbottom:"Botn texta",
image_align_left:"Vinstri",
image_align_right:"H\u00E6gri",
link_title:"Setja inn/breyta hlekk",
link_url:"Sl\u00F3\u00F0 hlekks",
link_target:"Target",
link_target_same:"Opna hlekk \u00ED sama glugga",
link_target_blank:"Opna hlekk \u00ED n\u00FDjum glugga",
link_titlefield:"Titill",
link_is_email:"Sl\u00F3\u00F0in sem \u00FE\u00FA sl\u00F3st inn vir\u00F0ist vera netfang, viltu b\u00E6ta vi\u00F0 mailto: forskeytinu?",
link_is_external:"Sl\u00F3\u00F0in sem \u00FE\u00FA sl\u00F3st inn vir\u00F0ist vera utana\u00F0komandi, viltu b\u00E6ta vi\u00F0 http:// forskeytinu?",
link_list:"Hlekkjalisti"
});