tinyMCE.addI18n('it.advanced',{
style_select:"Stili",
font_size:"Grandezza carattere",
fontdefault:"Famiglia carattere",
block:"Formato",
paragraph:"Paragrafo",
div:"Div",
address:"Indirizzo",
pre:"Preformattato",
h1:"Intestazione 1",
h2:"Intestazione 2",
h3:"Intestazione 3",
h4:"Intestazione 4",
h5:"Intestazione 5",
h6:"Intestazione 6",
blockquote:"Testo quotato",
code:"Codice",
samp:"Esempio codice",
dt:"Termine definizione",
dd:"Descrizione definizione",
bold_desc:"Grassetto (Ctrl+B)",
italic_desc:"Corsivo (Ctrl+I)",
underline_desc:"Sottolineato (Ctrl+U)",
striketrough_desc:"Barrato",
justifyleft_desc:"Allinea a sinistra",
justifycenter_desc:"Centra",
justifyright_desc:"Allinea a destra",
justifyfull_desc:"Giustifica",
bullist_desc:"Lista non ordinata",
numlist_desc:"Lista ordinata",
outdent_desc:"Sposta verso esterno",
indent_desc:"Sposta verso interno",
undo_desc:"Annulla (Ctrl+Z)",
redo_desc:"Ripristina (Ctrl+Y)",
link_desc:"Inserisci/modifica collegamento",
unlink_desc:"Togli collegamento",
image_desc:"Inserisci/modifica immagine",
cleanup_desc:"Pulisci codice disordinato",
code_desc:"Modifica sorgente HTML",
sub_desc:"Pedice",
sup_desc:"Apice",
hr_desc:"Inserisci riga orizzontale",
removeformat_desc:"Rimuovi formattazione",
custom1_desc:"La tua descrizione personalizzata qui",
forecolor_desc:"Seleziona colore testo",
backcolor_desc:"Seleziona colore sfondo",
charmap_desc:"Inserisci carattere speciale",
visualaid_desc:"Mostra/nascondi linee guida/elementi invisibili",
anchor_desc:"Inserisci/modifica ancora",
cut_desc:"Taglia",
copy_desc:"Copia",
paste_desc:"Incolla",
image_props_desc:"Propriet\u00E0 immagine",
newdocument_desc:"Nuovo documento",
help_desc:"Aiuto",
blockquote_desc:"Testo quotato",
clipboard_msg:"Copia/Taglia/Incolla non \u00E8 disponibile in Mozilla e Firefox..\r\nSi desidera avere maggiori informazioni su questo problema?",
path:"Percorso",
newdocument:"Sei sicuro di voler cancellare tutti i contenuti?",
toolbar_focus:"Vai ai pulsanti strumento - Alt+Q, Vai all'editor - Alt-Z, Vai al percorso dell'elemento - Alt-X",
more_colors:"Colori aggiuntivi"
});