tinyMCE.addI18n('ms.advanced_dlg',{
about_title:"Perihal TinyMCE",
about_general:"Perihal",
about_help:"Bantuan",
about_license:"Lesen",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Pengarang",
about_version:"Versi",
about_loaded:"Muatan plugins",
anchor_title:"Sisip/sunting sauh",
anchor_name:"Nama sauh",
code_title:"Penyunting HTML",
code_wordwrap:"Sisip perkataan",
colorpicker_title:"Pilih warna",
colorpicker_picker_tab:"Pemungut",
colorpicker_picker_title:"Pemungut warna",
colorpicker_palette_tab:"Palet",
colorpicker_palette_title:"Palet warna",
colorpicker_named_tab:"Dinamakan",
colorpicker_named_title:"Warna telah dinamakan",
colorpicker_color:"Warna:",
colorpicker_name:"Nama:",
charmap_title:"Pilih aksara sendiri",
image_title:"Sisip/sunting imej",
image_src:"Imej URL",
image_alt:"Huraian imej",
image_list:"Senarai imej",
image_border:"Sempadan",
image_dimensions:"Dimensi",
image_vspace:"Ruangan tegak",
image_hspace:"Ruangan ufuk",
image_align:"Penyelarian",
image_align_baseline:"Garis pangkal",
image_align_top:"Atas",
image_align_middle:"Tengah",
image_align_bottom:"Bawah",
image_align_texttop:"Teks atas",
image_align_textbottom:"Teks bawah",
image_align_left:"Kiri",
image_align_right:"Kanan",
link_title:"Sisip/sunting pautan",
link_url:"Pautan URL",
link_target:"Sasaran",
link_target_same:"Buka pautan dalam tetingkap yang sama",
link_target_blank:"Buka pautan dalam tetingkap yang sama",
link_titlefield:"Tajuk",
link_is_email:"URL yang anda masukkan adalah alamat emel, tambah \"mailto\": di awalan?",
link_is_external:"URL yang anda masukkan adalah pautan luar, tambah \"http://\" di awalan?",
link_list:"Senarai pautan"
});