tinyMCE.addI18n('nl.advanced_dlg',{
about_title:"Over TinyMCE",
about_general:"Info",
about_help:"Help",
about_license:"Licentie",
about_plugins:"Invoegtoepassingen",
about_plugin:"Invoegtoepassing",
about_author:"Auteur",
about_version:"Versie",
about_loaded:"Geladen Invoegtoepassingen",
anchor_title:"Anker invoegen/bewerken",
anchor_name:"Ankernaam",
code_title:"HTML Bron",
code_wordwrap:"Automatische terugloop",
colorpicker_title:"Kleuren",
colorpicker_picker_tab:"Alle kleuren",
colorpicker_picker_title:"Alle kleuren",
colorpicker_palette_tab:"Palet",
colorpicker_palette_title:"Paletkleuren",
colorpicker_named_tab:"Benoemd",
colorpicker_named_title:"Benoemde kleuren",
colorpicker_color:"Kleur:",
colorpicker_name:"Naam:",
charmap_title:"Symbolen",
image_title:"Afbeelding invoegen/bewerken",
image_src:"Bestand/URL",
image_alt:"Beschrijving",
image_list:"Lijst",
image_border:"Rand",
image_dimensions:"Afmetingen",
image_vspace:"Verticale ruimte",
image_hspace:"Horizontale ruimte",
image_align:"Uitlijning",
image_align_baseline:"Basislijn",
image_align_top:"Boven",
image_align_middle:"Midden",
image_align_bottom:"Onder",
image_align_texttop:"Bovenkant tekst",
image_align_textbottom:"Onderkant tekst",
image_align_left:"Links",
image_align_right:"Rechts",
link_title:"Link invoegen/bewerken",
link_url:"URL",
link_target:"Doel",
link_target_same:"Link in hetzelfde venster openen",
link_target_blank:"Link in een nieuw venster openen",
link_titlefield:"Titel",
link_is_email:"De ingevoerde URL lijkt op een e-mailadres. Wilt u de vereiste mailto: tekst voorvoegen?",
link_is_external:"De ingevoerde URL lijkt op een externe link. Wilt u de vereiste http:// tekst voorvoegen?",
link_list:"Link lijst"
});